services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\ResourceBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,Search,Timeline}'

    # Controller services.
    Bkstg\ResourceBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags:
            - { name: controller.service_arguments }
