<?php

namespace Bkstg\ResourceBundle\Repository;

use Bkstg\ResourceBundle\Entity\Resource;
use Doctrine\ORM\EntityRepository;
use MidnightLuke\GroupSecurityBundle\Model\GroupInterface;

/**
 * ResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceRepository extends EntityRepository
{
    public function findAllByGroupQuery(GroupInterface $group, bool $active = true)
    {
        $qb = $this->createQueryBuilder('r');
        return $qb
            ->join('r.groups', 'g')

            // Add conditions.
            ->andWhere($qb->expr()->eq('g', ':group'))
            ->andWhere($qb->expr()->eq('r.active', ':active'))

            // Add parameters.
            ->setParameter('group', $group)
            ->setParameter('active', $active)

            // Order by and get results.
            ->orderBy('r.pinned', 'DESC')
            ->addOrderBy('r.name', 'ASC')
            ->getQuery();
    }
}
