bkstg_resource_index:
    path: /
    defaults:
        _controller: Bkstg\ResourceController\Controller\ResourceController:indexAction
bkstg_resource_create:
    path: /create
    defaults:
        _controller: Bkstg\ResourceController\Controller\ResourceController:createAction
bkstg_resource_show:
    path: /{id}
    defaults:
        _controller: Bkstg\ResourceController\Controller\ResourceController:readAction
bkstg_resource_edit:
    path: /{id}/edit
    defaults:
        _controller: Bkstg\ResourceController\Controller\ResourceController:updateAction
bkstg_resource_delete:
    path: /{id}/delete
    defaults:
        _controller: Bkstg\ResourceController\Controller\ResourceController:deleteAction
