bkstg_resource_index:
    path: /
    defaults:
        _controller: Bkstg\ResourceBundle\Controller\ResourceController:indexAction
bkstg_resource_archive:
    path: /archive
    defaults:
        _controller: Bkstg\ResourceBundle\Controller\ResourceController:archiveAction
bkstg_resource_create:
    path: /create
    defaults:
        _controller: Bkstg\ResourceBundle\Controller\ResourceController:createAction
bkstg_resource_read:
    path: /{id}
    defaults:
        _controller: Bkstg\ResourceBundle\Controller\ResourceController:readAction
bkstg_resource_update:
    path: /{id}/edit
    defaults:
        _controller: Bkstg\ResourceBundle\Controller\ResourceController:updateAction
bkstg_resource_delete:
    path: /{id}/delete
    defaults:
        _controller: Bkstg\ResourceBundle\Controller\ResourceController:deleteAction
